/* THIS FILE HAS BEEN AUTOMATICALLY GENERATED BY LLnextgen. DO NOT EDIT */
#ifndef  __LLNEXTGEN_LL_H__
#define __LLNEXTGEN_LL_H__
#ifndef LL_NOTOKENS
#define EOFILE 256
#define VARSTOK 257
#define DOMAINSTOK 258
#define CONSTRAINTSTOK 259
#define SOLVETOK 260
#define ALLTOK 261
#define INTTYPE 262
#define BOOLTYPE 263
#define ARROWTOK 264
#define BRACKOPEN 265
#define BRACKCLOSE 266
#define MINUSTOK 267
#define PLUSTOK 268
#define STARTOK 269
#define POWTOK 270
#define COMMATOK 271
#define SEMITOK 272
#define COLONTOK 273
#define ISTOK 274
#define SMALLERTOK 275
#define GREATERTOK 276
#define NEQTOK 277
#define LEQTOK 278
#define GEQTOK 279
#define MODTOK 280
#define DIVTOK 281
#define PARENTOPEN 282
#define PARENTCLOSE 283
#define VARTOK 284
#define DECTOK 285
#define RANGETOK 286
#define MAXTOK 287
#define MINTOK 288
#define ABSTOK 289
#define ANYTOK 290
#endif
#define LL_MAXTOKNO 290
#define LL_MISSINGEOF (-1)
#define LL_DELETE (0)
#define LL_VERSION 0x000505L
#define LL_NEW_TOKEN (-2)
#define LL_THREAD_SAFE
#include "problem.h"
struct LLthis {
	int LLscnt_[25];
	int LLtcnt_[35];
	int LLcsymb_;
	int LLsymb_;
	int LLreissue_;
	Problem LLdata_;
};
#define LLsymb (LLthis->LLsymb_)
#define LLdata (LLthis->LLdata_)
#define LLreissue (LLthis->LLreissue_)
void parser(Problem LLuserData, Problem *LLretval);
const char *LLgetSymbol(int);
#endif
